-- Seed de templates de WhatsApp Business API
-- Ejecutar este SQL para crear los templates iniciales

INSERT INTO whatsapp_templates (
    id,
    nombre,
    categoria,
    lenguaje,
    contenido,
    variables,
    aprobado,
    wa_template_name,
    activo,
    descripcion,
    ejemplo,
    created_at,
    updated_at
) VALUES (
    gen_random_uuid(),
    'confirmacion_consentimiento',
    'SISTEMA',
    'es',
    'Hola {{nombre}}, bienvenido a FairPadel. Para recibir notificaciones por WhatsApp, responde SI a este mensaje. Puedes cancelar en cualquier momento respondiendo NO.',
    ARRAY['nombre'],
    false,
    'fairpadel_consent_confirmation',
    true,
    'Mensaje para solicitar confirmación de consentimiento (doble opt-in)',
    'Hola Juan, bienvenido a FairPadel. Para recibir notificaciones por WhatsApp, responde SI a este mensaje. Puedes cancelar en cualquier momento respondiendo NO.',
    NOW(),
    NOW()
), (
    gen_random_uuid(),
    'bienvenida_consentimiento',
    'SISTEMA',
    'es',
    '✅ ¡Perfecto {{nombre}}! Ahora recibirás notificaciones de FairPadel por WhatsApp. Te enviaremos recordatorios de reservas, actualizaciones de torneos y más.',
    ARRAY['nombre'],
    false,
    'fairpadel_welcome',
    true,
    'Mensaje de bienvenida después de confirmar consentimiento',
    '✅ ¡Perfecto Juan! Ahora recibirás notificaciones de FairPadel por WhatsApp. Te enviaremos recordatorios de reservas, actualizaciones de torneos y más.',
    NOW(),
    NOW()
), (
    gen_random_uuid(),
    'confirmacion_reserva',
    'RESERVA',
    'es',
    'Hola {{nombre}}, tu reserva fue confirmada:\n\n📅 Fecha: {{fecha}}\n🎾 Cancha: {{cancha}}\n⏰ Hora: {{hora}}\n\nNos vemos en la cancha!',
    ARRAY['nombre', 'fecha', 'cancha', 'hora'],
    false,
    'fairpadel_reserva_confirmada',
    true,
    'Confirmación de reserva de cancha',
    'Hola Juan, tu reserva fue confirmada:\n\n📅 Fecha: 15/01/2026\n🎾 Cancha: Cancha 1\n⏰ Hora: 18:00\n\nNos vemos en la cancha!',
    NOW(),
    NOW()
), (
    gen_random_uuid(),
    'recordatorio_reserva_24h',
    'RECORDATORIO',
    'es',
    '⏰ Recordatorio: Tenés una reserva mañana!\n\n📅 {{fecha}}\n🎾 {{cancha}}\n⏰ {{hora}}\n\nSi no podés asistir, cancelá con anticipación.',
    ARRAY['fecha', 'cancha', 'hora'],
    false,
    'fairpadel_recordatorio_24h',
    true,
    'Recordatorio 24 horas antes de la reserva',
    '⏰ Recordatorio: Tenés una reserva mañana!\n\n📅 15/01/2026\n🎾 Cancha 1\n⏰ 18:00\n\nSi no podés asistir, cancelá con anticipación.',
    NOW(),
    NOW()
), (
    gen_random_uuid(),
    'recordatorio_reserva_4h',
    'RECORDATORIO',
    'es',
    '🔔 ¡Te esperamos en unas horas!\n\n📅 {{fecha}}\n🎾 {{cancha}}\n⏰ {{hora}}\n\nNo olvides tu equipo. ¡Buen partido!',
    ARRAY['fecha', 'cancha', 'hora'],
    false,
    'fairpadel_recordatorio_4h',
    true,
    'Recordatorio 4 horas antes de la reserva',
    '🔔 ¡Te esperamos en unas horas!\n\n📅 15/01/2026\n🎾 Cancha 1\n⏰ 18:00\n\nNo olvides tu equipo. ¡Buen partido!',
    NOW(),
    NOW()
), (
    gen_random_uuid(),
    'inscripcion_torneo',
    'TORNEO',
    'es',
    '¡Felicidades {{nombre}}! Te inscribiste en {{torneo}}\n\n🎾 Categoría: {{categoria}}\n👤 Pareja: {{pareja}}\n\nTe avisaremos cuando se publique el fixture.',
    ARRAY['nombre', 'torneo', 'categoria', 'pareja'],
    false,
    'fairpadel_inscripcion_torneo',
    true,
    'Confirmación de inscripción a torneo',
    '¡Felicidades Juan! Te inscribiste en Torneo Verano 2026\n\n🎾 Categoría: 3ra Masculina\n👤 Pareja: Pedro Gomez\n\nTe avisaremos cuando se publique el fixture.',
    NOW(),
    NOW()
), (
    gen_random_uuid(),
    'fixture_publicado',
    'TORNEO',
    'es',
    '¡El fixture de {{torneo}} ya está disponible!\n\n🎾 Tu primer partido:\n📅 {{fecha}}\n⏰ {{hora}}\n🆚 Vs: {{rival}}\n\nVer fixture: {{link}}',
    ARRAY['torneo', 'fecha', 'hora', 'rival', 'link'],
    false,
    'fairpadel_fixture_publicado',
    true,
    'Notificación de fixture publicado',
    '¡El fixture de Torneo Verano 2026 ya está disponible!\n\n🎾 Tu primer partido:\n📅 20/01/2026\n⏰ 19:00\n🆚 Vs: Martinez/Lopez\n\nVer fixture: https://fairpadel.com/fixture/123',
    NOW(),
    NOW()
) ON CONFLICT (nombre) DO NOTHING;
