-- AlterTable
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "banner_url" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "bio" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "instagram" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "facebook" TEXT;
